// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLCz-xBKuCLsdT0qrl11Wl4NDrbbRKL0A',
    appId: '1:810267291243:web:67ad9c9030dd7f531c8b2e',
    messagingSenderId: '810267291243',
    projectId: 'agilizadiarista',
    authDomain: 'agilizadiarista.firebaseapp.com',
    storageBucket: 'agilizadiarista.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB81pIXqX_PZIydS-KJuDVbmy9aq3_CBWs',
    appId: '1:810267291243:android:11c763fa67c7aa571c8b2e',
    messagingSenderId: '810267291243',
    projectId: 'agilizadiarista',
    storageBucket: 'agilizadiarista.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk8Lm1-AADU5sbJ8KbsLjj5f_qdRWXR3U',
    appId: '1:810267291243:ios:aa4a9029ec5cd0e51c8b2e',
    messagingSenderId: '810267291243',
    projectId: 'agilizadiarista',
    storageBucket: 'agilizadiarista.appspot.com',
    iosClientId: '810267291243-t8a46su4kd2bu2ka2i495a2a528rl8d7.apps.googleusercontent.com',
    iosBundleId: 'diarista.agiliza.agilizadiarista',
  );
}
